/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessSettingsRouteImport } from './routes/business-settings'
import { Route as CallsRouteImport } from './routes/calls'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSettingsRoute = BusinessSettingsRouteImport.update({
  id: '/business-settings',
  path: '/business-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-settings': typeof BusinessSettingsRoute
  '/calls': typeof CallsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-settings': typeof BusinessSettingsRoute
  '/calls': typeof CallsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-settings': typeof BusinessSettingsRoute
  '/calls': typeof CallsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/business-settings' | '/calls'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/business-settings' | '/calls'
  id: '__root__' | '/' | '/business-settings' | '/calls'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessSettingsRoute: typeof BusinessSettingsRoute
  CallsRoute: typeof CallsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-settings': {
      id: '/business-settings'
      path: '/business-settings'
      fullPath: '/business-settings'
      preLoaderRoute: typeof BusinessSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessSettingsRoute: BusinessSettingsRoute,
  CallsRoute: CallsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
